[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
http = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"